name: CD Trigger

on:
    issue_comment:
        types: [created, edited]

jobs:
  run-cd-workflows:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
#      - name: Deploy to FirebaseDistribution
#        if: contains(github.event.comment.body, '/deploy')
#        run: |
#          echo "Triggering debug and release deployments..."
#          gh workflow run deploy-debug.yml
#          gh workflow run deploy-release.yml
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check workspace
        run: echo ${{ github.workspace }}

      - name: Add deploy comment to PR
        if: contains(github.event.comment.body, '/deploy')
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
#        uses: actions/github-script@v6
#        with:
#          script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '🚀 deploy start\n## 작업 사항\n\n'
#            });
